/* RAYYOKA V2 — production-ready browser POS + cloud sync */
'use strict';
const SUPABASE_URL='https://dmhlfrnjvjgsooamioak.supabase.co';
const SUPABASE_KEY='sb_publishable_HvY0X0eDKCZ8dMKsLAZICg_6MBsmMUi';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const SERVICE=.10,VAT=.13,LOCAL='rayyoka_v2_data';
const DEFAULT_MENU=[['Veg Momo','Momo',120,'🥟'],['Chicken Momo','Momo',150,'🥟'],['Veg Fry Momo','Momo',140,'🥟'],['Chicken Fry Momo','Momo',170,'🥟'],['Veg Chawmin','Chawmin',120,'🍜'],['Chicken Chawmin','Chawmin',150,'🍜'],['Egg Chawmin','Chawmin',140,'🍜'],['Mix Chawmin','Chawmin',180,'🍜'],['Veg Fried Rice','Fried Rice',120,'🍚'],['Egg Fried Rice','Fried Rice',140,'🍚'],['Chicken Fried Rice','Fried Rice',160,'🍚'],['Mix Fried Rice','Fried Rice',190,'🍚'],['Veg Noodles','Noodles',120,'🍜'],['Chicken Noodles','Noodles',150,'🍜'],['Egg Noodles','Noodles',140,'🍜'],['Mix Noodles','Noodles',180,'🍜'],['Black Tea','Drinks',30,'🍵'],['Milk Tea','Drinks',40,'☕'],['Black Coffee','Drinks',50,'☕'],['Milk Coffee','Drinks',60,'☕'],['Soft Drink','Drinks',80,'🥤']].map((x,i)=>({id:'local-'+(i+1),name:x[0],category:x[1],price:x[2],cost:Math.round(x[2]*.45),emoji:x[3],available:true}));
const NAV=[['dashboard','⌂','Dashboard'],['sales','＋','New Sale'],['orders','▣','Orders'],['kitchen','♨','Kitchen'],['inventory','▤','Inventory'],['menu','☷','Menu'],['customers','♙','Customers'],['reports','▥','Reports'],['expenses','₹','Expenses'],['settings','⚙','Settings']];
let state={page:new URLSearchParams(location.search).get('customer')==='1'?'dashboard':'dashboard',customerMode:new URLSearchParams(location.search).get('customer')==='1',menu:DEFAULT_MENU,orders:[],inventory:[],expenses:[],customers:[],cart:[],cat:'All',customerCart:[],settings:{businessName:'RAYYOKA FOODS',phone:'',address:'',service:.10,vat:.13}};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), money=n=>'NPR '+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2});
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2600)}
function modal(html){$('modalBox').innerHTML=html;$('modal').classList.add('show')};function closeModal(){$('modal').classList.remove('show')} window.closeModal=closeModal;
function localLoad(){try{const x=JSON.parse(localStorage.getItem(LOCAL));if(x)Object.assign(state,x)}catch(e){console.warn(e)}}
function localSave(){localStorage.setItem(LOCAL,JSON.stringify({...state,cart:[],customerCart:[]}))}
function nav(){if(state.customerMode)return;document.querySelector('.sidebar').classList.remove('open');$('nav').innerHTML=NAV.map(n=>`<button class="nav-item ${state.page===n[0]?'active':''}" data-page="${n[0]}"><i>${n[1]}</i><span>${n[2]}</span></button>`).join('');document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page))}
function go(page){state.page=page;nav();renderPage();$('heading').textContent=({dashboard:'Dashboard',sales:'New Sale',orders:'Orders',kitchen:'Kitchen Display',inventory:'Inventory',menu:'Menu Management',customers:'Customers',reports:'Business Reports',expenses:'Expenses',settings:'Settings'})[page]||'Customer Order';$('content').scrollTop=0}
function renderPage(){const c=$('content');if(state.customerMode){c.innerHTML=customerPage();bindCustomer();renderCustomerMenu();return}const pages={dashboard:dashboardPage,sales:salesPage,orders:ordersPage,kitchen:kitchenPage,inventory:inventoryPage,menu:menuPage,customers:customersPage,reports:reportsPage,expenses:expensesPage,settings:settingsPage};c.innerHTML=pages[state.page]();bindCommon();if(state.page==='sales')renderPOS();if(state.page==='orders')renderOrders();if(state.page==='kitchen')renderKitchen();if(state.page==='inventory')renderInventory();if(state.page==='menu')renderMenu();if(state.page==='customers')renderCustomers();if(state.page==='reports')renderReports();if(state.page==='expenses')renderExpenses();if(state.page==='settings')renderSettings()}
function shell(body){return `<section class="page active">${body}</section>`}
function dashboardPage(){const today=new Date().toISOString().slice(0,10),sales=state.orders.filter(o=>o.status!=='Cancelled'),rev=sales.reduce((a,o)=>a+o.total,0),todayRev=sales.filter(o=>String(o.time||'').slice(0,10)===today).reduce((a,o)=>a+o.total,0),exp=state.expenses.reduce((a,x)=>a+x.amount,0);return shell(`<div class="hero"><div><span class="eyebrow">RAYYOKA V2 • BUSINESS CONTROL</span><h1>Run the business.<br><span>Simply.</span></h1><p>Professional POS, kitchen, inventory, customers and finance in one system.</p></div><button class="btn primary" onclick="go('sales')">＋ New Sale</button></div><div class="stats"><div class="stat"><span>Total Revenue</span><strong>${money(rev)}</strong><small>All completed sales</small></div><div class="stat"><span>Orders</span><strong>${sales.length}</strong><small>Recorded orders</small></div><div class="stat"><span>Today's Sales</span><strong>${money(todayRev)}</strong><small>Local business date</small></div><div class="stat"><span>Estimated Profit</span><strong>${money(rev-exp)}</strong><small>Revenue minus expenses</small></div></div><div class="section-head"><h2>Quick Access</h2></div><div class="quick"><button onclick="go('sales')"><b>＋ New Sale</b><small>Fast checkout</small></button><button onclick="go('kitchen')"><b>♨ Kitchen</b><small>Live order queue</small></button><button onclick="go('inventory')"><b>▤ Inventory</b><small>Stock control</small></button><button onclick="go('reports')"><b>▥ Reports</b><small>Business analytics</small></button></div><div class="section-head"><h2>Recent Orders</h2><button class="link" onclick="go('orders')">View all →</button></div><div class="table">${ordersRows(state.orders.slice(0,7))}</div>`)}
function salesPage(){return shell(`<div class="section-head"><div><span class="eyebrow">POINT OF SALE</span><h1>New Sale</h1></div><span class="pill">Service ${state.settings.service*100}% • VAT ${state.settings.vat*100}%</span></div><div class="pos"><div class="panel menu-panel"><div class="panel-head"><div><h2>RAYYOKA Menu</h2><small>Tap an item to add it</small></div><input id="search" class="input search" placeholder="Search menu..."></div><div id="cats" class="cats"></div><div id="foods" class="foods"></div></div><div class="panel cart-panel"><h2>Current Order</h2><label>Customer</label><input id="customer" class="input" placeholder="Walk-in Customer"><div class="two"><div><label>Type</label><select id="orderType" class="input"><option>Dine-in</option><option>Takeaway</option><option>Delivery</option></select></div><div><label>Payment</label><select id="payment" class="input"><option>Cash</option><option>QR / Digital</option><option>Card</option><option>Credit</option></select></div></div><div id="cartItems" class="cart-items"></div><div class="bill"><div><span>Subtotal</span><b id="subtotal">NPR 0</b></div><div><span>Discount</span><input id="discount" class="input mini" type="number" min="0" value="0"></div><div><span>Service</span><b id="service">NPR 0</b></div><div><span>VAT</span><b id="vat">NPR 0</b></div><div class="total"><span>Grand Total</span><b id="grand">NPR 0</b></div></div><button id="complete" class="btn primary full">Complete Sale</button><button id="clear" class="btn outline full">Clear</button></div></div>`)}
function ordersPage(){return shell(`<div class="section-head"><div><span class="eyebrow">SALES HISTORY</span><h1>Orders</h1></div><button id="export" class="btn dark">Export CSV</button></div><div class="table">${ordersRows(state.orders)}</div>`)}
function ordersRows(arr){if(!arr.length)return `<div class="empty">No orders yet.</div>`;return `<table><thead><tr><th>Order</th><th>Customer</th><th>Type</th><th>Total</th><th>Status</th><th>Time</th></tr></thead><tbody>${arr.map(o=>`<tr onclick="orderDetails('${esc(o.id)}')"><td><b>${esc(o.id)}</b></td><td>${esc(o.name||'Walk-in')}</td><td>${esc(o.orderType||'')}</td><td><b>${money(o.total)}</b></td><td><span class="status ${String(o.status).toLowerCase()}">${esc(o.status)}</span></td><td>${fmtDate(o.time)}</td></tr>`).join('')}</tbody></table>`}
function kitchenPage(){return shell(`<div class="section-head"><div><span class="eyebrow">KITCHEN DISPLAY</span><h1>Live Orders</h1></div><button class="btn outline" onclick="renderKitchen()">↻ Refresh</button></div><div id="kitchen" class="kitchen-grid"></div>`)}
function inventoryPage(){return shell(`<div class="section-head"><div><span class="eyebrow">STOCK CONTROL</span><h1>Inventory</h1></div><button class="btn primary" onclick="addStock()">＋ Add Stock</button></div><div class="stats mini-stats"><div class="stat"><span>Items</span><strong>${state.inventory.length}</strong></div><div class="stat"><span>Low Stock</span><strong>${state.inventory.filter(x=>x.qty<=x.min).length}</strong></div><div class="stat"><span>Stock Units</span><strong>${state.inventory.reduce((a,x)=>a+Number(x.qty),0).toFixed(0)}</strong></div></div><div class="table" id="inventoryTable"></div>`)}
function menuPage(){return shell(`<div class="section-head"><div><span class="eyebrow">PRODUCTS</span><h1>Menu Management</h1></div><button class="btn primary" onclick="addMenu()">＋ Add Product</button></div><div id="menuAdmin" class="menu-admin"></div>`)}
function customersPage(){return shell(`<div class="section-head"><div><span class="eyebrow">CRM</span><h1>Customers</h1></div></div><div class="table" id="customersTable"></div>`)}
function reportsPage(){const rev=state.orders.filter(o=>o.status!=='Cancelled').reduce((a,o)=>a+o.total,0),exp=state.expenses.reduce((a,x)=>a+x.amount,0),avg=state.orders.length?rev/state.orders.length:0;return shell(`<div class="section-head"><div><span class="eyebrow">ANALYTICS</span><h1>Business Reports</h1></div><button class="btn dark" onclick="exportCSV()">Export CSV</button></div><div class="report-grid"><div class="report"><span>Gross Revenue</span><strong>${money(rev)}</strong><small>Completed sales</small></div><div class="report"><span>Expenses</span><strong>${money(exp)}</strong><small>Recorded expenses</small></div><div class="report"><span>Estimated Profit</span><strong>${money(rev-exp)}</strong><small>Revenue minus expenses</small></div><div class="report"><span>Average Order</span><strong>${money(avg)}</strong><small>Per order</small></div></div><div class="section-head"><h2>Top Selling Items</h2></div><div class="table">${topItems()}</div>`)}
function expensesPage(){return shell(`<div class="section-head"><div><span class="eyebrow">FINANCE</span><h1>Expenses</h1></div></div><div class="expense-form panel"><input id="expenseName" class="input" placeholder="Expense description"><input id="expenseAmount" class="input" type="number" min="0" placeholder="Amount (NPR)"><button class="btn primary" id="addExpense">Add Expense</button></div><div class="table" id="expensesTable"></div>`)}
function settingsPage(){return shell(`<div class="section-head"><div><span class="eyebrow">SYSTEM</span><h1>Settings & Backup</h1></div></div><div class="settings-grid"><div class="panel"><h2>Business Profile</h2><label>Business Name</label><input id="businessName" class="input"><label>Phone</label><input id="businessPhone" class="input"><label>Address</label><input id="businessAddress" class="input"><div class="two"><div><label>Service Charge %</label><input id="serviceRate" class="input" type="number" min="0" step="0.1"></div><div><label>VAT %</label><input id="vatRate" class="input" type="number" min="0" step="0.1"></div></div><button id="saveSettings" class="btn primary">Save Settings</button></div><div class="panel"><h2>Data Safety</h2><p class="muted">Cloud sync is enabled when signed in. Browser backup is also available.</p><button class="btn dark full" onclick="backup()">Download Backup</button><button class="btn outline full" onclick="document.getElementById('restoreFile').click()">Restore Backup</button><input id="restoreFile" type="file" accept="application/json" hidden><button class="btn danger full" onclick="resetData()">Reset Local Data</button><hr><p class="muted">Customer ordering link:</p><code>${location.origin}${location.pathname}?customer=1</code></div></div>`)}
function customerPage(){return `<section class="customer-shell"><header class="customer-head"><div class="brand"><div class="brandmark">RY</div><div><h1>RAYYOKA</h1><small>FLAVORS THAT CONNECT</small></div></div><span class="pill">Online Ordering</span></header><div class="customer-hero"><span class="eyebrow">RAYYOKA FOODS</span><h1>Good food. Easy ordering.</h1><p>Select your favourites and place your order directly.</p></div><div class="pos customer-pos"><div class="panel menu-panel"><div class="panel-head"><div><h2>Menu</h2><small>Freshly prepared</small></div><input id="csearch" class="input search" placeholder="Search menu..."></div><div id="ccats" class="cats"></div><div id="cfoods" class="foods"></div></div><div class="panel cart-panel"><h2>Your Order</h2><label>Name</label><input id="cname" class="input" placeholder="Your name"><label>Phone</label><input id="cphone" class="input" placeholder="98XXXXXXXX"><div class="two"><div><label>Type</label><select id="ctype" class="input"><option>Pickup</option><option>Delivery</option><option>Dine-in</option></select></div><div><label>Table</label><input id="ctable" class="input" placeholder="Optional"></div></div><label>Address</label><input id="caddress" class="input" placeholder="Delivery address (if needed)"><div id="ccart" class="cart-items"></div><div class="bill"><div><span>Subtotal</span><b id="csub">NPR 0</b></div><div><span>Service</span><b id="cservice">NPR 0</b></div><div><span>VAT</span><b id="cvat">NPR 0</b></div><div class="total"><span>Total</span><b id="ctotal">NPR 0</b></div></div><button id="placeCustomer" class="btn primary full">Place Order</button></div></div></section>`}
function bindCommon(){if($('search'))$('search').oninput=renderPOS;if($('discount'))$('discount').oninput=renderPOSCart;if($('complete'))$('complete').onclick=completeSale;if($('clear'))$('clear').onclick=()=>{state.cart=[];renderPOSCart()};if($('export'))$('export').onclick=exportCSV;if($('addExpense'))$('addExpense').onclick=addExpense;if($('saveSettings'))$('saveSettings').onclick=saveSettings;if($('restoreFile'))$('restoreFile').onchange=e=>e.target.files[0]&&restore(e.target.files[0])}
function cats(prefix=''){return ['All','Momo','Chawmin','Fried Rice','Noodles','Drinks'].map(x=>`<button class="cat ${state.cat===x?'active':''}" data-cat="${prefix}${x}">${x}</button>`).join('')}
function filtered(search=''){return state.menu.filter(x=>x.available!==false&&(state.cat==='All'||x.category===state.cat)&&x.name.toLowerCase().includes(search.toLowerCase()))}
function renderPOS(){if(!$('foods'))return;$('cats').innerHTML=cats();document.querySelectorAll('#cats .cat').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;renderPOS()});const a=filtered($('search')?.value||'');$('foods').innerHTML=a.map(x=>`<button class="food" onclick="addCart('${x.id}')"><span class="emoji">${x.emoji||'🍽️'}</span><h3>${esc(x.name)}</h3><small>${esc(x.category)}</small><strong>${money(x.price)}</strong></button>`).join('')||'<div class="empty">No menu items found.</div>';renderPOSCart()}
function addCart(id){const m=state.menu.find(x=>String(x.id)===String(id));if(!m)return;const x=state.cart.find(x=>String(x.id)===String(id));if(x)x.qty++;else state.cart.push({id:m.id,name:m.name,price:Number(m.price),cost:Number(m.cost||0),qty:1});renderPOSCart();toast('Added to order')} window.addCart=addCart;
function calc(cart,discount=0){const subtotal=cart.reduce((a,x)=>a+x.price*x.qty,0),d=Math.min(Math.max(Number(discount)||0,0),subtotal),base=subtotal-d,service=base*Number(state.settings.service),vat=(base+service)*Number(state.settings.vat);return{subtotal,discount:d,service,vat,total:base+service+vat}}
function cartRows(cart,target){const box=$(target);if(!box)return;box.innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><div><b>${esc(x.name)}</b><small>${money(x.price)} each</small></div><div class="qty"><button onclick="changeQty('${x.id}',-1,'${target}')">−</button><b>${x.qty}</b><button onclick="changeQty('${x.id}',1,'${target}')">＋</button></div><strong>${money(x.price*x.qty)}</strong></div>`).join(''):'<div class="empty">Your order is empty.</div>'}
function changeQty(id,delta,target='cartItems'){const cart=target==='ccart'?state.customerCart:state.cart;const x=cart.find(x=>String(x.id)===String(id));if(!x)return;x.qty+=delta;if(x.qty<=0)cart.splice(cart.indexOf(x),1);target==='ccart'?renderCustomerCart():renderPOSCart()} window.changeQty=changeQty;
function renderPOSCart(){if(!$('cartItems'))return;cartRows(state.cart,'cartItems');const t=calc(state.cart,$('discount')?.value||0);['subtotal','service','vat','grand'].forEach((id,i)=>$(id).textContent=money([t.subtotal,t.service,t.vat,t.total][i]))}
function newOrder(extra){const t=calc(state.cart,extra.discount||0);return{id:'RY-'+Date.now().toString().slice(-7),name:extra.name||'Walk-in Customer',phone:extra.phone||'',address:extra.address||'',table:extra.table||'',orderType:extra.orderType||'Dine-in',payment:extra.payment||'Cash',items:state.cart.map(x=>({name:x.name,price:x.price,cost:x.cost||0,qty:x.qty})),...t,status:'New',time:new Date().toISOString()}}
async function completeSale(){if(!state.cart.length)return toast('Add at least one item');const o=newOrder({name:$('customer').value.trim()||'Walk-in Customer',orderType:$('orderType').value,payment:$('payment').value,discount:Number($('discount').value||0)});state.orders.unshift(o);state.cart=[];localSave();renderPOS();const ok=await cloudSaveOrder(o);modal(`<div class="success">✓</div><h2>Sale Completed</h2><p>${esc(o.id)} • <b>${money(o.total)}</b></p><div class="modal-actions"><button class="btn dark" onclick="printReceipt('${o.id}')">Print Receipt</button><button class="btn primary" onclick="closeModal();go('orders')">Done</button></div>`);toast(ok?'Saved to cloud':'Saved locally; cloud sync unavailable')} window.completeSale=completeSale;
function renderOrders(){$('content').querySelector('.table').innerHTML=ordersRows(state.orders)}
function renderKitchen(){const live=state.orders.filter(o=>!['Completed','Cancelled'].includes(o.status));$('kitchen').innerHTML=live.length?live.map(o=>`<div class="kcard"><div class="khead"><b>${esc(o.id)}</b><span>${fmtDate(o.time)}</span></div><h3>${esc(o.name)}</h3><p>${o.items.map(i=>`${i.qty}× ${esc(i.name)}`).join('<br>')}</p><strong>${money(o.total)}</strong><div class="k-actions">${o.status==='New'?`<button class="btn small" onclick="setStatus('${o.id}','Preparing')">Start</button>`:''}${o.status==='Preparing'?`<button class="btn small" onclick="setStatus('${o.id}','Ready')">Ready</button>`:''}${o.status==='Ready'?`<button class="btn small" onclick="setStatus('${o.id}','Completed')">Complete</button>`:''}<button class="btn small danger" onclick="setStatus('${o.id}','Cancelled')">Cancel</button></div></div>`).join(''):'<div class="empty">No live kitchen orders.</div>'}
async function setStatus(id,status){const o=state.orders.find(x=>x.id===id);if(!o)return;o.status=status;localSave();renderKitchen();await cloudStatus(o,status);toast(`${id} marked ${status}`)} window.setStatus=setStatus;
function renderInventory(){const box=$('inventoryTable');if(!box)return;box.innerHTML=state.inventory.length?`<table><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Minimum</th><th>State</th><th></th></tr></thead><tbody>${state.inventory.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${Number(x.qty).toFixed(2)}</td><td>${esc(x.unit)}</td><td>${x.min}</td><td><span class="status ${x.qty<=x.min?'cancelled':'completed'}">${x.qty<=x.min?'Low':'OK'}</span></td><td><button class="btn small" onclick="adjustStock('${x.id}')">Update</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No inventory items. Add your first item.</div>'}
async function adjustStock(id){const x=state.inventory.find(x=>String(x.id)===String(id));if(!x)return;const v=prompt(`New quantity for ${x.name}`,x.qty);if(v===null)return;const q=Number(v);if(!Number.isFinite(q)||q<0)return toast('Invalid quantity');x.qty=q;localSave();await cloudInventory(x);renderInventory();toast('Stock updated')} window.adjustStock=adjustStock;
async function addStock(){const name=prompt('Item name');if(!name)return;const qty=Number(prompt('Quantity','0'));if(!Number.isFinite(qty))return;const unit=prompt('Unit','kg')||'kg',min=Number(prompt('Minimum quantity','2'))||0;const x={id:'local-'+Date.now(),name,qty,unit,min};state.inventory.push(x);localSave();await cloudCreateInventory(x);renderInventory();toast('Inventory item added')}
function renderMenu(){const box=$('menuAdmin');box.innerHTML=state.menu.map(x=>`<div class="menu-admin-row"><span class="emoji">${x.emoji||'🍽️'}</span><div><b>${esc(x.name)}</b><small>${esc(x.category)} • Cost ${money(x.cost||0)}</small></div><strong>${money(x.price)}</strong><button class="btn small" onclick="editMenu('${x.id}')">Edit</button></div>`).join('')}
async function addMenu(){const name=prompt('Product name');if(!name)return;const category=prompt('Category: Momo, Chawmin, Fried Rice, Noodles, Drinks')||'Momo';const price=Number(prompt('Selling price (NPR)','120'));if(!Number.isFinite(price))return;const cost=Number(prompt('Cost price (NPR)',Math.round(price*.45)));const emoji=prompt('Emoji','🍽️')||'🍽️';const x={id:'local-'+Date.now(),name,category,price,cost,emoji,available:true};state.menu.push(x);localSave();await cloudCreateMenu(x);renderMenu();toast('Product added')} window.addMenu=addMenu;
async function editMenu(id){const x=state.menu.find(x=>String(x.id)===String(id));if(!x)return;const p=prompt('Selling price',x.price);if(p===null)return;x.price=Number(p);x.available=confirm('Keep this item available?');localSave();await cloudUpdateMenu(x);renderMenu();toast('Menu updated')} window.editMenu=editMenu;
function renderCustomers(){const map={};state.orders.forEach(o=>{const k=o.phone||o.name||'Walk-in';if(!map[k])map[k]={name:o.name||'Walk-in',phone:o.phone||'',orders:0,spent:0};map[k].orders++;map[k].spent+=o.total});const rows=Object.values(map);$('customersTable').innerHTML=rows.length?`<table><thead><tr><th>Customer</th><th>Phone</th><th>Orders</th><th>Spent</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.phone)}</td><td>${x.orders}</td><td>${money(x.spent)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Customer data will appear after orders.</div>'}
function topItems(){const m={};state.orders.forEach(o=>o.items.forEach(i=>{m[i.name]=(m[i.name]||0)+i.qty}));const rows=Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,10);return rows.length?`<table><thead><tr><th>Item</th><th>Units Sold</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x[0])}</td><td><b>${x[1]}</b></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No sales data yet.</div>'}
function renderReports(){}
function renderExpenses(){const box=$('expensesTable');box.innerHTML=state.expenses.length?`<table><thead><tr><th>Description</th><th>Category</th><th>Amount</th><th>Date</th></tr></thead><tbody>${state.expenses.map(x=>`<tr><td>${esc(x.description)}</td><td>${esc(x.category||'General')}</td><td><b>${money(x.amount)}</b></td><td>${esc(x.date||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No expenses recorded.</div>'}
async function addExpense(){const description=$('expenseName').value.trim(),amount=Number($('expenseAmount').value);if(!description||!Number.isFinite(amount)||amount<=0)return toast('Enter a description and valid amount');const x={id:'local-'+Date.now(),description,amount,category:'General',date:new Date().toISOString().slice(0,10)};state.expenses.unshift(x);localSave();await cloudCreateExpense(x);$('expenseName').value='';$('expenseAmount').value='';renderExpenses();toast('Expense added')}
function renderSettings(){$('businessName').value=state.settings.businessName||'';$('businessPhone').value=state.settings.phone||'';$('businessAddress').value=state.settings.address||'';$('serviceRate').value=Number(state.settings.service)*100;$('vatRate').value=Number(state.settings.vat)*100}
async function saveSettings(){state.settings={businessName:$('businessName').value.trim()||'RAYYOKA FOODS',phone:$('businessPhone').value.trim(),address:$('businessAddress').value.trim(),service:Number($('serviceRate').value||10)/100,vat:Number($('vatRate').value||13)/100};localSave();await cloudSaveSettings();toast('Settings saved')}
function backup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rayyoka-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
function restore(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);Object.assign(state,x);localSave();renderPage();toast('Backup restored')}catch(e){toast('Invalid backup file')}};r.readAsText(file)}
function resetData(){if(!confirm('Reset local data? Cloud data will not be deleted.'))return;localStorage.removeItem(LOCAL);location.reload()}
function exportCSV(){const rows=[['Order','Customer','Type','Total','Status','Time'],...state.orders.map(o=>[o.id,o.name,o.orderType,o.total,o.status,o.time])];download('rayyoka-orders.csv',rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')} function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function orderDetails(id){const o=state.orders.find(x=>x.id===id);if(!o)return;modal(`<h2>${esc(o.id)}</h2><p><b>${esc(o.name)}</b> • ${esc(o.orderType)} • ${esc(o.payment)}</p><div class="receipt-items">${o.items.map(i=>`<div>${i.qty} × ${esc(i.name)} <b>${money(i.qty*i.price)}</b></div>`).join('')}</div><div class="bill"><div><span>Subtotal</span><b>${money(o.subtotal)}</b></div><div><span>Service</span><b>${money(o.service)}</b></div><div><span>VAT</span><b>${money(o.vat)}</b></div><div class="total"><span>Total</span><b>${money(o.total)}</b></div></div><button class="btn primary full" onclick="closeModal()">Close</button>`)} window.orderDetails=orderDetails;
function printReceipt(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const w=window.open('','_blank','width=420,height=650');w.document.write(`<html><head><title>${o.id}</title><style>body{font-family:Arial;padding:24px;max-width:360px;margin:auto}h1{text-align:center}.r{display:flex;justify-content:space-between;margin:8px 0}.total{font-size:20px;font-weight:bold}</style></head><body><h1>RAYYOKA FOODS</h1><p style="text-align:center">FLAVORS THAT CONNECT</p><hr><p>${o.id}<br>${fmtDate(o.time)}<br>${esc(o.name)}</p>${o.items.map(i=>`<div class="r"><span>${i.qty} × ${esc(i.name)}</span><b>${money(i.qty*i.price)}</b></div>`).join('')}<hr><div class="r"><span>Subtotal</span><b>${money(o.subtotal)}</b></div><div class="r"><span>Service</span><b>${money(o.service)}</b></div><div class="r"><span>VAT</span><b>${money(o.vat)}</b></div><div class="r total"><span>Total</span><b>${money(o.total)}</b></div><hr><p style="text-align:center">Thank you for choosing RAYYOKA</p><script>window.print()<\/script></body></html>`);w.document.close()} window.printReceipt=printReceipt;
function bindCustomer(){if($('csearch'))$('csearch').oninput=renderCustomerMenu;if($('placeCustomer'))$('placeCustomer').onclick=placeCustomerOrder}
function renderCustomerMenu(){if(!$('cfoods'))return;$('ccats').innerHTML=cats('c');document.querySelectorAll('#ccats .cat').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat.slice(1);renderCustomerMenu()});const a=filtered($('csearch')?.value||'');$('cfoods').innerHTML=a.map(x=>`<button class="food" onclick="addCustomerCart('${x.id}')"><span class="emoji">${x.emoji||'🍽️'}</span><h3>${esc(x.name)}</h3><small>${esc(x.category)}</small><strong>${money(x.price)}</strong></button>`).join('');renderCustomerCart()}
function addCustomerCart(id){const m=state.menu.find(x=>String(x.id)===String(id)),x=state.customerCart.find(x=>String(x.id)===String(id));if(!m)return;if(x)x.qty++;else state.customerCart.push({id:m.id,name:m.name,price:Number(m.price),qty:1});renderCustomerCart()} window.addCustomerCart=addCustomerCart;
function renderCustomerCart(){cartRows(state.customerCart,'ccart');const t=calc(state.customerCart,0);if($('csub'))$('csub').textContent=money(t.subtotal);if($('cservice'))$('cservice').textContent=money(t.service);if($('cvat'))$('cvat').textContent=money(t.vat);if($('ctotal'))$('ctotal').textContent=money(t.total)}
async function placeCustomerOrder(){if(!state.customerCart.length)return toast('Add items first');const name=$('cname').value.trim();if(!name)return toast('Enter your name');const t=calc(state.customerCart,0),o={id:'RY-'+Date.now().toString().slice(-7),name,phone:$('cphone').value.trim(),address:$('caddress').value.trim(),table:$('ctable').value.trim(),orderType:$('ctype').value,payment:'Pending',items:state.customerCart.map(x=>({name:x.name,price:x.price,cost:0,qty:x.qty})),...t,status:'New',time:new Date().toISOString()};const ok=await cloudSaveOrder(o,true);if(ok){state.customerCart=[];renderCustomerCart();modal(`<div class="success">✓</div><h2>Order Received</h2><p>Your order number is <b>${esc(o.id)}</b>.</p><p>Total: <b>${money(o.total)}</b></p><button class="btn primary full" onclick="closeModal()">Done</button>`)}else toast('Could not send order. Please try again.')}
function fmtDate(x){return x?new Date(x).toLocaleString('en-NP',{dateStyle:'medium',timeStyle:'short'}):'—'}
async function cloudSaveOrder(o){if(!sb)return false;try{const {data:u}=await sb.auth.getUser();const payload={order_number:o.id,customer_name:o.name,order_type:o.orderType,status:'new',payment_method:o.payment==='Pending'?'Cash':o.payment,payment_status:o.payment==='Pending'?'pending':'paid',subtotal:o.subtotal,discount:o.discount||0,service_charge:o.service,vat:o.vat,total:o.total,delivery_address:o.address||null,table_number:o.table||null,created_by:u?.user?.id||null};const {data:ord,error}=await sb.from('orders').insert(payload).select('id').single();if(error)throw error;const {error:e}=await sb.from('order_items').insert(o.items.map(i=>({order_id:ord.id,item_name:i.name,unit_price:i.price,quantity:i.qty,line_total:i.price*i.qty,notes:null})));if(e)throw e;o._cloudId=ord.id;return true}catch(e){console.warn('cloud order',e);return false}}
async function cloudStatus(o,status){if(!sb||!o._cloudId)return;try{await sb.from('orders').update({status:status.toLowerCase()}).eq('id',o._cloudId)}catch(e){console.warn(e)}}
async function cloudInventory(x){if(!sb||String(x.id).startsWith('local-'))return;try{await sb.from('inventory_items').update({quantity:Number(x.qty),minimum_quantity:Number(x.min),updated_at:new Date().toISOString()}).eq('id',x.id)}catch(e){console.warn(e)}}
async function cloudCreateInventory(x){if(!sb)return;try{const {data}=await sb.from('inventory_items').insert({name:x.name,unit:x.unit,quantity:x.qty,minimum_quantity:x.min,cost_per_unit:0,active:true}).select().single();if(data)x.id=data.id;localSave()}catch(e){console.warn(e)}}
async function cloudCreateMenu(x){if(!sb)return;try{const {data:cat}=await sb.from('menu_categories').select('id').ilike('name',x.category).maybeSingle();const {data}=await sb.from('menu_items').insert({category_id:cat?.id||null,name:x.name,price:x.price,cost_price:x.cost||0,emoji:x.emoji,available:true}).select().single();if(data)x.id=data.id;localSave()}catch(e){console.warn(e)}}
async function cloudUpdateMenu(x){if(!sb||String(x.id).startsWith('local-'))return;try{await sb.from('menu_items').update({price:x.price,available:x.available,updated_at:new Date().toISOString()}).eq('id',x.id)}catch(e){console.warn(e)}}
async function cloudCreateExpense(x){if(!sb)return;try{const {data:u}=await sb.auth.getUser();await sb.from('expenses').insert({description:x.description,amount:x.amount,category:x.category,expense_date:x.date,created_by:u?.user?.id||null})}catch(e){console.warn(e)}}
async function cloudSaveSettings(){if(!sb)return;try{await sb.from('business_settings').update({business_name:state.settings.businessName,phone:state.settings.phone,address:state.settings.address,service_charge_rate:state.settings.service,vat_rate:state.settings.vat,updated_at:new Date().toISOString()}).not('id','is',null)}catch(e){console.warn(e)}}
async function cloudLoad(){if(!sb||state.customerMode)return;try{const [o,i,m,c,e,s]=await Promise.all([sb.from('orders').select('*,order_items(*)').order('created_at',{ascending:false}).limit(500),sb.from('inventory_items').select('*').eq('active',true).order('name'),sb.from('menu_items').select('*,menu_categories(name)').eq('available',true).order('name'),sb.from('customers').select('*').order('name').limit(500),sb.from('expenses').select('*').order('expense_date',{ascending:false}).limit(500),sb.from('business_settings').select('*').limit(1).maybeSingle()]);if(!o.error&&o.data){state.orders=o.data.map(q=>({id:q.order_number,name:q.customer_name,phone:'',address:q.delivery_address||'',table:q.table_number||'',orderType:q.order_type,payment:q.payment_method,items:(q.order_items||[]).map(i=>({name:i.item_name,qty:i.quantity,price:Number(i.unit_price),cost:0})),subtotal:Number(q.subtotal),discount:Number(q.discount),service:Number(q.service_charge),vat:Number(q.vat),total:Number(q.total),status:({new:'New',preparing:'Preparing',ready:'Ready',completed:'Completed',cancelled:'Cancelled'}[q.status]||q.status),time:q.created_at,_cloudId:q.id}));if(!i.error&&i.data)state.inventory=i.data.map(x=>({id:x.id,name:x.name,unit:x.unit,qty:Number(x.quantity),min:Number(x.minimum_quantity)}));if(!m.error&&m.data?.length)state.menu=m.data.map(x=>({id:x.id,name:x.name,category:x.menu_categories?.name||'Other',price:Number(x.price),cost:Number(x.cost_price),emoji:x.emoji||'🍽️',available:x.available}));if(!c.error)state.customers=c.data||[];if(!e.error)state.expenses=e.data?.map(x=>({id:x.id,description:x.description,amount:Number(x.amount),category:x.category,date:x.expense_date}))||[];if(!s.error&&s.data)state.settings={businessName:s.data.business_name,phone:s.data.phone||'',address:s.data.address||'',service:Number(s.data.service_charge_rate),vat:Number(s.data.vat_rate)};localSave()}catch(e){console.warn('cloud load',e)}}
function authScreen(message=''){if(state.customerMode||$('auth'))return;const d=document.createElement('div');d.id='auth';d.className='auth';d.innerHTML=`<div class="auth-card"><div class="brand center"><div class="brandmark">RY</div><div><h1>RAYYOKA</h1><small>BUSINESS SYSTEM</small></div></div><p>Secure Owner / Staff Login</p>${message?`<div class="error">${esc(message)}</div>`:''}<label>Email</label><input id="loginEmail" class="input" type="email" autocomplete="username" placeholder="Email"><label>Password</label><input id="loginPassword" class="input" type="password" autocomplete="current-password" placeholder="Password"><button id="loginBtn" class="btn primary full">Sign In</button><small class="muted">Use your Supabase account credentials.</small></div>`;document.body.appendChild(d);$('loginBtn').onclick=login;$('loginPassword').onkeydown=e=>e.key==='Enter'&&login()}
async function login(){const b=$('loginBtn'),email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||!password)return toast('Enter email and password');b.disabled=true;b.textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email,password});if(error){b.disabled=false;b.textContent='Sign In';$('auth')?.remove();authScreen(error.message)}}
async function start(){localLoad();$('date').textContent=new Date().toLocaleDateString('en-NP',{weekday:'long',year:'numeric',month:'long',day:'numeric'});setInterval(()=>$('clock').textContent=new Date().toLocaleTimeString('en-NP',{hour:'2-digit',minute:'2-digit'}),1000);if(state.customerMode){renderPage();return}nav();if(!sb){authScreen('Cloud connection unavailable.');return}const {data:{user}}=await sb.auth.getUser();if(!user){authScreen();return}const {data:p}=await sb.from('profiles').select('full_name,role').eq('id',user.id).maybeSingle();if(p?.role&&p.role!=='owner'&&p.role!=='manager'&&p.role!=='staff'){authScreen('This account is not authorized.');return}const foot=$('sidebarFoot');if(foot)foot.innerHTML=`<span class="online">●</span> Cloud Connected<br>${esc(p?.full_name||user.email)} • ${esc(p?.role||'staff')}<br><button class="signout" id="signout">Sign out</button>`;setTimeout(()=>{if($('signout'))$('signout').onclick=()=>sb.auth.signOut()},0);await cloudLoad();renderPage();sb.channel('rayyoka-live').on('postgres_changes',{event:'*',schema:'public',table:'orders'},()=>cloudLoad()).subscribe()}
sb?.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'&&!state.customerMode){$('auth')?.remove();authScreen();if($('sidebarFoot'))$('sidebarFoot').innerHTML='<span class="online">●</span> Signed out'}});
window.go=go;window.renderKitchen=renderKitchen;window.renderInventory=renderInventory;window.renderMenu=renderMenu;window.renderCustomers=renderCustomers;window.renderReports=renderReports;window.renderExpenses=renderExpenses;window.addStock=addStock;window.addMenu=addMenu;window.backup=backup;window.resetData=resetData;window.exportCSV=exportCSV;
start();
