(()=>{'use strict';
const URL='https://dmhlfrnjvjgsooamioak.supabase.co',KEY='sb_publishable_HvY0X0eDKCZ8dMKsLAZICg_6MBsmMUi',db=window.supabase.createClient(URL,KEY);let menu=[],cart=[],cat='All',me=null;
const $=id=>document.getElementById(id),money=n=>'NPR '+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2}),toast=t=>{const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)};
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show')}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){const {data,error}=await db.from('menu_items').select('id,name,description,price,emoji,image_url,available,menu_categories(name)').eq('available',true).order('name');if(error){toast('Menu could not load');return}menu=(data||[]).map(x=>({...x,category:x.menu_categories?.name||'Other'}));renderCats();renderMenu();const {data:s}=await db.auth.getSession();await setUser(s.session?.user||null);db.auth.onAuthStateChange((_e,session)=>setUser(session?.user||null))}
async function setUser(user){me=user;if(user){let {data,error}=await db.rpc('get_my_ry_customer');if(!data){const pending=localStorage.getItem('rayyoka_pending_ry');if(pending){const r=await db.rpc('link_ry_customer_auth',{p_ry_id:pending});if(!r.error)data=r.data}}if(data){localStorage.setItem('rayyoka_ry_customer',JSON.stringify(data));me.ry=data}else if(user){me.ry=null} $('accountBtn').textContent=me.ry?'RY '+me.ry.ry_id:'Account';$('ordersSection').classList.remove('hidden');await loadOrders()}else{$('accountBtn').textContent='Login / Register';$('ordersSection').classList.add('hidden')}}
function renderCats(){const cats=['All',...new Set(menu.map(x=>x.category))];$('cats').innerHTML=cats.map(x=>`<button class="cat ${cat===x?'active':''}" data-cat="${esc(x)}">${esc(x)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;renderCats();renderMenu()})}
function renderMenu(){const q=(window.menuSearch||'').toLowerCase();const items=menu.filter(x=>(cat==='All'||x.category===cat)&&x.name.toLowerCase().includes(q));$('menu').innerHTML=items.map(x=>`<button class="food" data-add="${x.id}">${x.image_url?`<img src="${esc(x.image_url)}" alt="" style="width:100%;height:130px;object-fit:cover;border-radius:12px">`:`<div class="emoji">${x.emoji||'🍽️'}</div>`}<h3>${esc(x.name)}</h3><small>${esc(x.category)}</small>${x.description?`<p class="muted">${esc(x.description)}</p>`:''}<strong>${money(x.price)}</strong></button>`).join('')||'<p class="muted">No items available.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add))}
function add(id){const m=menu.find(x=>x.id===id);if(!m)return;const x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id,name:m.name,price:Number(m.price),qty:1});renderCart();toast('Added to cart')}
function qty(id,d){const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);renderCart()}
function totals(){const sub=cart.reduce((a,x)=>a+x.price*x.qty,0),svc=sub*.10,vat=(sub+svc)*.13;return{sub,svc,vat,total:sub+svc+vat}}
function renderCart(){const n=cart.reduce((a,x)=>a+x.qty,0);$('cartCount').textContent=n;$('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartRow"><div><b>${esc(x.name)}</b><small style="display:block;color:#777">${money(x.price)} each</small></div><div class="qty"><button data-q="${x.id}" data-d="-1">−</button><b>${x.qty}</b><button data-q="${x.id}" data-d="1">＋</button></div><strong>${money(x.price*x.qty)}</strong></div>`).join(''):'<p class="muted">Your cart is empty.</p>';document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>qty(b.dataset.q,Number(b.dataset.d)));const t=totals();$('cartBill').innerHTML=`<div><span>Subtotal</span><b>${money(t.sub)}</b></div><div><span>Service 10%</span><b>${money(t.svc)}</b></div><div><span>VAT 13%</span><b>${money(t.vat)}</b></div><div class="total"><span>Total</span><b>${money(t.total)}</b></div>`}
function account(){if(me?.ry){openModal(`<h2>RY Account</h2><p><b>${esc(me.ry.name)}</b></p><p class="muted">${esc(me.ry.email||me.user.email)}</p><p>RY ID: <b>${esc(me.ry.ry_id)}</b></p><button class="primary full" id="logout">Sign out</button>`);$('logout').onclick=async()=>{await db.auth.signOut();closeModal();toast('Signed out')}}else openAuth('login')}
function openAuth(mode='login',msg=''){openModal(`<div class="tabs"><button id="loginTab" class="tab ${mode==='login'?'active':''}">Login</button><button id="regTab" class="tab ${mode==='register'?'active':''}">First-time registration</button></div><div id="authBody"></div>`);$('loginTab').onclick=()=>openAuth('login');$('regTab').onclick=()=>openAuth('register');authBody(mode,msg)}
function authBody(mode,msg){$('authBody').innerHTML=mode==='login'?`<h2>Welcome back</h2><p class="muted">Use your RY account to order.</p><div class="field"><label>Email</label><input id="aEmail" type="email" autocomplete="email"></div><div class="field"><label>Password</label><input id="aPass" type="password" autocomplete="current-password"></div><p id="aErr" class="error" style="display:${msg?'block':'none'}">${esc(msg)}</p><button id="aGo" class="primary full">Login</button>`:`<h2>Create your RY account</h2><p class="muted">Register once. Next time, simply log in.</p><div class="field"><label>Full name</label><input id="aName" autocomplete="name"></div><div class="field"><label>Phone</label><input id="aPhone" autocomplete="tel"></div><div class="field"><label>Email</label><input id="aEmail" type="email" autocomplete="email"></div><div class="field"><label>Password</label><input id="aPass" type="password" minlength="8" autocomplete="new-password" placeholder="At least 8 characters"></div><p id="aErr" class="error" style="display:none"></p><button id="aGo" class="primary full">Create RY account</button>`;$('aGo').onclick=mode==='login'?login:register}
async function login(){const email=$('aEmail').value.trim(),password=$('aPass').value;if(!email||!password)return showErr('Email and password are required');$('aGo').disabled=true;$('aGo').textContent='Logging in…';const {error}=await db.auth.signInWithPassword({email,password});if(error){$('aGo').disabled=false;$('aGo').textContent='Login';return showErr(error.message)}closeModal();toast('Welcome back');await setUser((await db.auth.getSession()).data.session.user)}
async function register(){const name=$('aName').value.trim(),phone=$('aPhone').value.trim(),email=$('aEmail').value.trim().toLowerCase(),password=$('aPass').value;if(!name||!phone||!email||password.length<8)return showErr('Name, phone, email and an 8+ character password are required');$('aGo').disabled=true;$('aGo').textContent='Creating…';const r=await db.rpc('register_ry_customer',{p_full_name:name,p_phone:phone,p_email:email});if(r.error){$('aGo').disabled=false;$('aGo').textContent='Create RY account';return showErr(r.error.message)}const ry=r.data;localStorage.setItem('rayyoka_pending_ry',ry.ry_id);const s=await db.auth.signUp({email,password,options:{data:{ry_id:ry.ry_id,name,phone}}});if(s.error){$('aGo').disabled=false;$('aGo').textContent='Create RY account';return showErr(s.error.message)}if(s.data.session){const l=await db.rpc('link_ry_customer_auth',{p_ry_id:ry.ry_id});if(l.error)return showErr(l.error.message);localStorage.removeItem('rayyoka_pending_ry');closeModal();toast('RY account created');await setUser(s.data.user)}else{openAuth('login','Registration complete. Check your email if verification is required, then log in. Your RY ID is '+ry.ry_id)}}
function showErr(t){$('aErr').textContent=t;$('aErr').style.display='block'}
function checkout(){if(!cart.length)return toast('Add items first');if(!me?.ry)return openAuth('login','Please register or log in before placing an order.');openModal(`<h2>Checkout</h2><div class="field"><label>Order type</label><select id="oType"><option>Pickup</option><option>Delivery</option><option>Dine-in</option></select></div><div class="field"><label>Name</label><input id="oName" value="${esc(me.ry.name)}"></div><div class="field"><label>Phone</label><input id="oPhone" value="${esc(me.ry.phone)}"></div><div class="field"><label>Delivery address (required for Delivery)</label><input id="oAddress"></div><p class="muted">Payment is confirmed by RAYYOKA staff. Delivery charge is confirmed according to distance.</p><button id="place" class="primary full">Place order</button>`);$('oType').onchange=()=>{};$('place').onclick=placeOrder}
async function placeOrder(){const type=$('oType').value,name=$('oName').value.trim(),phone=$('oPhone').value.trim(),address=$('oAddress').value.trim();if(type==='Delivery'&&!address)return showErr('Delivery address is required');const btn=$('place');btn.disabled=true;btn.textContent='Placing order…';const {data,error}=await db.rpc('place_public_order',{p_customer_name:name,p_phone:phone,p_order_type:type,p_address:address,p_items:cart.map(x=>({menu_item_id:x.id,quantity:x.qty})),p_delivery_charge:0,p_ry_customer_id:me.ry.ry_id});if(error){btn.disabled=false;btn.textContent='Place order';return alert(error.message)}cart=[];renderCart();closeModal();toast('Order '+data.order_number+' received');await loadOrders();$('ordersSection').scrollIntoView({behavior:'smooth'})}
async function loadOrders(){if(!me?.ry)return;const {data,error}=await db.from('orders').select('order_number,customer_name,order_type,status,total,created_at,order_items(item_name,quantity)').eq('ry_customer_id',me.ry.ry_id).order('created_at',{ascending:false}).limit(20);if(error){$('myOrders').innerHTML='<p class="muted">Order history unavailable.</p>';return}$('myOrders').innerHTML=data?.length?data.map(o=>`<div class="orderCard"><div style="display:flex;justify-content:space-between;gap:10px"><b>${esc(o.order_number)}</b><span class="status">${esc(o.status)}</span></div><p>${(o.order_items||[]).map(i=>`${i.quantity} × ${esc(i.item_name)}`).join('<br>')}</p><strong>${money(o.total)}</strong><small style="display:block;color:#777;margin-top:6px">${new Date(o.created_at).toLocaleString('en-NP')} • ${esc(o.order_type)}</small></div>`).join(''):'<p class="muted">No orders yet.</p>'}
$('cartBtn').onclick=()=>{$('drawer').classList.add('open');$('shade').classList.add('open')};$('closeCart').onclick=closeCart;$('shade').onclick=closeCart;function closeCart(){$('drawer').classList.remove('open');$('shade').classList.remove('open')}$('checkoutBtn').onclick=checkout;$('accountBtn').onclick=account;$('closeModal').onclick=closeModal;load();renderCart();
})();