(()=>{'use strict';
const URL='https://dmhlfrnjvjgsooamioak.supabase.co',KEY='sb_publishable_HvY0X0eDKCZ8dMKsLAZICg_6MBsmMUi',db=window.supabase.createClient(URL,KEY);let menu=[],cart=[],cat='All',me=null;
const $=id=>document.getElementById(id),money=n=>'NPR '+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2}),toast=t=>{const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openModal(h){$('modalContent').innerHTML=h;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show')}function showErr(t){const x=$('aErr');if(x){x.textContent=t;x.style.display='block'}}
async function load(){const {data,error}=await db.from('menu_items').select('id,name,description,price,emoji,image_url,available,menu_categories(name)').eq('available',true).order('name');if(error){toast('Menu could not load');return}menu=(data||[]).map(x=>({...x,category:x.menu_categories?.name||'Other'}));renderCats();renderMenu();restoreCustomer()}
function restoreCustomer(){try{const x=JSON.parse(localStorage.getItem('rayyoka_customer')||'null');if(x?.ry_id){me={ry:x};setAccountUI();loadOrders()}}catch(e){localStorage.removeItem('rayyoka_customer')}}
function setAccountUI(){$('accountBtn').textContent=me?.ry?'RY '+me.ry.ry_id:'Register / My RY';if(me?.ry)$('ordersSection').classList.remove('hidden')}
function renderCats(){const cats=['All',...new Set(menu.map(x=>x.category))];$('cats').innerHTML=cats.map(x=>`<button class="cat ${cat===x?'active':''}" data-cat="${esc(x)}">${esc(x)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;renderCats();renderMenu()})}
function renderMenu(){const items=menu.filter(x=>cat==='All'||x.category===cat);$('menu').innerHTML=items.map(x=>`<button class="food" data-add="${x.id}">${x.image_url?`<img src="${esc(x.image_url)}" alt="" style="width:100%;height:130px;object-fit:cover;border-radius:12px">`:`<div class="emoji">${x.emoji||'🍽️'}</div>`}<h3>${esc(x.name)}</h3><small>${esc(x.category)}</small>${x.description?`<p class="muted">${esc(x.description)}</p>`:''}<strong>${money(x.price)}</strong></button>`).join('')||'<p class="muted">No items available.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add))}
function add(id){const m=menu.find(x=>x.id===id);if(!m)return;const x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id,name:m.name,price:Number(m.price),qty:1});renderCart();toast('Added to cart')}
function qty(id,d){const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);renderCart()}
function totals(){const sub=cart.reduce((a,x)=>a+x.price*x.qty,0),svc=sub*.10,vat=(sub+svc)*.13;return{sub,svc,vat,total:sub+svc+vat}}
function renderCart(){const n=cart.reduce((a,x)=>a+x.qty,0);$('cartCount').textContent=n;$('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartRow"><div><b>${esc(x.name)}</b><small style="display:block;color:#777">${money(x.price)} each</small></div><div class="qty"><button data-q="${x.id}" data-d="-1">−</button><b>${x.qty}</b><button data-q="${x.id}" data-d="1">＋</button></div><strong>${money(x.price*x.qty)}</strong></div>`).join(''):'<p class="muted">Your cart is empty.</p>';document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>qty(b.dataset.q,Number(b.dataset.d)));const t=totals();$('cartBill').innerHTML=`<div><span>Subtotal</span><b>${money(t.sub)}</b></div><div><span>Service 10%</span><b>${money(t.svc)}</b></div><div><span>VAT 13%</span><b>${money(t.vat)}</b></div><div class="total"><span>Total</span><b>${money(t.total)}</b></div>`}
function account(){if(me?.ry){openModal(`<h2>My RY Account</h2><p><b>${esc(me.ry.name)}</b></p><p>Phone: ${esc(me.ry.phone)}</p>${me.ry.email?`<p>Email: ${esc(me.ry.email)}</p>`:''}<p>RY ID: <b>${esc(me.ry.ry_id)}</b></p><p class="muted">You can order without email verification.</p><button class="primary full" id="logout">Use another account</button>`);$('logout').onclick=()=>{localStorage.removeItem('rayyoka_customer');me=null;setAccountUI();$('ordersSection').classList.add('hidden');closeModal();toast('Account cleared')}}else register()}
function register(){openModal(`<h2>Create your RY account</h2><p class="muted">No email verification and no password required. Register once with your phone.</p><div class="field"><label>Full name</label><input id="aName" autocomplete="name"></div><div class="field"><label>Mobile number</label><input id="aPhone" type="tel" autocomplete="tel" placeholder="98XXXXXXXX"></div><div class="field"><label>Email <span class="muted">(optional)</span></label><input id="aEmail" type="email" autocomplete="email"></div><p id="aErr" class="error" style="display:none"></p><button id="aGo" class="primary full">Create my RY ID</button>`);$('aGo').onclick=createCustomer}
async function createCustomer(){const name=$('aName').value.trim(),phone=$('aPhone').value.trim(),email=$('aEmail').value.trim().toLowerCase();if(!name||!phone)return showErr('Name and mobile number are required');$('aGo').disabled=true;$('aGo').textContent='Creating RY ID…';const {data,error}=await db.rpc('register_ry_customer',{p_full_name:name,p_phone:phone,p_email:email||null});if(error){$('aGo').disabled=false;$('aGo').textContent='Create my RY ID';return showErr(error.message)}me={ry:data};localStorage.setItem('rayyoka_customer',JSON.stringify(data));setAccountUI();closeModal();toast('Welcome! Your RY ID is '+data.ry_id);}
function checkout(){if(!cart.length)return toast('Add items first');if(!me?.ry)return register();openModal(`<h2>Checkout</h2><div class="field"><label>Order type</label><select id="oType"><option>Pickup</option><option>Delivery</option><option>Dine-in</option></select></div><div class="field"><label>Name</label><input id="oName" value="${esc(me.ry.name)}"></div><div class="field"><label>Phone</label><input id="oPhone" value="${esc(me.ry.phone)}"></div><div class="field"><label>Delivery address (required for Delivery)</label><input id="oAddress"></div><p class="muted">Payment is confirmed by RAYYOKA staff. Delivery charge is confirmed according to distance.</p><button id="place" class="primary full">Place order</button>`);$('place').onclick=placeOrder}
async function placeOrder(){const type=$('oType').value,name=$('oName').value.trim(),phone=$('oPhone').value.trim(),address=$('oAddress').value.trim();if(!name||!phone)return alert('Name and phone are required');if(type==='Delivery'&&!address)return alert('Delivery address is required');const btn=$('place');btn.disabled=true;btn.textContent='Placing order…';const {data,error}=await db.rpc('place_public_order',{p_customer_name:name,p_phone:phone,p_order_type:type,p_address:address,p_items:cart.map(x=>({menu_item_id:x.id,quantity:x.qty})),p_delivery_charge:0,p_ry_customer_id:me.ry.ry_id});if(error){btn.disabled=false;btn.textContent='Place order';return alert(error.message)}cart=[];renderCart();closeModal();toast('Order '+data.order_number+' received');await loadOrders();$('ordersSection').scrollIntoView({behavior:'smooth'})}
async function loadOrders(){if(!me?.ry)return;const {data,error}=await db.from('orders').select('order_number,customer_name,order_type,status,total,created_at,order_items(item_name,quantity)').eq('ry_customer_id',me.ry.ry_id).order('created_at',{ascending:false}).limit(20);if(error){$('myOrders').innerHTML='<p class="muted">Order history will appear here after your orders are processed.</p>';return}$('myOrders').innerHTML=data?.length?data.map(o=>`<div class="orderCard"><div style="display:flex;justify-content:space-between;gap:10px"><b>${esc(o.order_number)}</b><span class="status">${esc(o.status)}</span></div><p>${(o.order_items||[]).map(i=>`${i.quantity} × ${esc(i.item_name)}`).join('<br>')}</p><strong>${money(o.total)}</strong><small style="display:block;color:#777;margin-top:6px">${new Date(o.created_at).toLocaleString('en-NP')} • ${esc(o.order_type)}</small></div>`).join(''):'<p class="muted">No orders yet.</p>'}
$('cartBtn').onclick=()=>{$('drawer').classList.add('open');$('shade').classList.add('open')};$('closeCart').onclick=closeCart;$('shade').onclick=closeCart;function closeCart(){$('drawer').classList.remove('open');$('shade').classList.remove('open')}$('checkoutBtn').onclick=checkout;$('accountBtn').onclick=account;$('closeModal').onclick=closeModal;load();renderCart();
})();